# -*- coding: utf-8 -*-

BTN_ADMIN_PANEL = "👑 ورود به پنل ادمین"
BTN_EXIT_ADMIN_PANEL = "↩️ خروج از پنل"
BTN_BACK_TO_ADMIN_MENU = "بازگشت به منوی ادمین"
CMD_CANCEL = "/cancel"
CMD_SKIP = "/skip"

(
    ADMIN_MENU, PLAN_MENU, REPORTS_MENU, USER_MANAGEMENT_MENU, PLAN_NAME,
    PLAN_PRICE, PLAN_DAYS, PLAN_GB, PLAN_CATEGORY,
    EDIT_PLAN_NAME, EDIT_PLAN_PRICE, EDIT_PLAN_DAYS, EDIT_PLAN_GB, EDIT_PLAN_CATEGORY,
    MANAGE_USER_ID, MANAGE_USER_ACTION, MANAGE_USER_AMOUNT, GET_CUSTOM_NAME,
    REDEEM_GIFT, CHARGE_AMOUNT, CHARGE_RECEIPT, SETTINGS_MENU, BACKUP_MENU,
    BROADCAST_MENU, BROADCAST_MESSAGE, BROADCAST_CONFIRM, BROADCAST_TO_USER_ID,
    BROADCAST_TO_USER_MESSAGE, RESTORE_UPLOAD, AWAIT_SETTING_VALUE,
    # Account actions
    TRANSFER_RECIPIENT_ID, TRANSFER_AMOUNT, TRANSFER_CONFIRM,
    GIFT_FROM_BALANCE_AMOUNT, GIFT_FROM_BALANCE_CONFIRM,
    # Support ticket
    SUPPORT_TICKET_OPEN,
    # Admin manage user's services
    MANAGE_SERVICE_ACTION
) = range(37)

ADMIN_SETTINGS_MENU = 100
GIFT_CODES_MENU = 101
PROMO_CODE_ENTRY = 102
CHARGE_PROMO_CODE = 103

# Admin Promo Code creation
(
    PROMO_GET_CODE, PROMO_GET_PERCENT, PROMO_GET_MAX_USES,
    PROMO_GET_EXPIRES, PROMO_GET_FIRST_PURCHASE
) = range(300, 305)