# src/config_template.py
BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
ADMIN_ID = 0 
PANEL_DOMAIN = "YOUR_PANEL_DOMAIN_HERE"
ADMIN_PATH = "YOUR_ADMIN_SECRET_PATH_HERE"
SUB_PATH = "YOUR_SUBSCRIPTION_SECRET_PATH_HERE" 
API_KEY = "YOUR_HIDDIFY_API_KEY_HERE"
SUB_DOMAINS = []
SUPPORT_USERNAME = "YOUR_SUPPORT_USERNAME"